### ISSUE TITLE
Make `docs.rs` documentation for all crates in the workspace build

### ISSUE THREAD

**Issue by virtualritz** [virtualritz/after-effects#57]
This requires:

- In each `Cargo.toml`:

  ```toml
  [package]
  default-target = "x86_64-apple-darwin"
  ```

  The default `docs.rs` build is on Linux which probably not work, even if the SDK headers were found?

- Downloading the macOS SDK inside `build.rs` and extracting it before the build commences

- ?
